spring:
    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://sccn1048.bmwgroup.net:3306/?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
            username: MASTER_DATA_FULL_LOAD
            password: 1qaz2wsx
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 250
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
    jooq:
        sql-dialect: mysql


application:
    database-to-export: MASTER_DATA_FULL_LOAD
    ignored-table-names:
        - databasechangelog
        - LKUP_MAIN
        - DATABASECHANGELOG
        - DATABASECHANGELOGLOCK
        - databasechangeloglock
        - jhi_authority
        - jhi_user
        - jhi_date_time_wrapper
        - jhi_persistent_audit_event
        - jhi_persistent_audit_evt_data
        - jhi_user_authority
        - interface_log
        - QRTZ_BLOB_TRIGGERS
        - QRTZ_CALENDARS
        - QRTZ_CRON_TRIGGERS
        - QRTZ_FIRED_TRIGGERS
        - QRTZ_JOB_DETAILS
        - QRTZ_LOCKS
        - QRTZ_PAUSED_TRIGGER_GRPS
        - QRTZ_SCHEDULER_STATE
        - QRTZ_SIMPLE_TRIGGERS
        - QRTZ_SIMPROP_TRIGGERS
        - QRTZ_TRIGGERS
    export:
        path: ./MASTER_DATA_FULL_LOAD.jh
        type: jdl
